import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

test('Owner test sender attachment makes the named owner workspace canonical without plaintext credential access', () => {
  const portal = readFileSync(new URL('../portal-worker.js', import.meta.url), 'utf8');
  const worker = readFileSync(new URL('../worker.js', import.meta.url), 'utf8');
  assert.match(portal, /owner\/test-tenant\/attach-maqtomate-test-sender/);
  assert.match(portal, /owner\/test-tenant\/validate-saved-credential/);
  assert.match(portal, /maqtomate_owned_meta_test_asset/);
  assert.match(portal, /legacy_owner_test_retired/);
  assert.match(portal, /encrypted_credential_handoff/);
  assert.match(portal, /credential_plaintext_accessed: false/);
  assert.match(portal, /INSERT INTO tenant_secret_envelopes/);
  assert.match(portal, /DELETE FROM tenant_secret_envelopes/);
  assert.match(portal, /owner-test-retired-/);
  assert.match(portal, /ON CONFLICT\(user_id, client_id\)/);
  assert.match(portal, /connection_status = 'PHONE_FOUND', webhook_status = 'VERIFIED'/);
  assert.doesNotMatch(portal, /webhook_status = 'WEBHOOK_VERIFIED'/);
  assert.match(portal, /OWNER_TEST_BRIDGE/);
  assert.match(portal, /bridge\.credentialHealth\(\)/);
  assert.match(portal, /bridge\.renewCredential\(replacementToken\)/);
  assert.match(portal, /sendOwnerControlledTest/);
  assert.match(portal, /send-controlled-test/);
  assert.match(portal, /Send controlled test to private recipient/);
  assert.doesNotMatch(portal, /X-Maqtomate-Internal-Token/);
  assert.match(portal, /owner\/test-tenant\/renew-meta-token/);
  assert.match(portal, /type="password"/);
  assert.match(portal, /owner\.test_tenant\.credential_renewal_bridge_failed/);
  assert.match(portal, /bridge_http_status: bridgeHttpStatus/);
  assert.match(portal, /bridge_response_class: bridgeResponseClass/);
  assert.match(portal, /credential_plaintext_accessed: false/);
  assert.doesNotMatch(portal, /meta_access_token:\s*replacementToken\s*}\s*\}\);/);
  assert.match(portal, /Maqtomate-owned test sender/);
  assert.match(worker, /business_name = 'Maqtomate Owner Test Tenant'/);
  assert.match(worker, /await import\('cloudflare:workers'\)/);
  assert.match(worker, /export class OwnerTestCredentialBridge extends WorkerEntrypointBase/);
  assert.match(worker, /async credentialHealth\(\)/);
  assert.match(worker, /async renewCredential\(replacementToken\)/);
  assert.match(worker, /async sendControlledTest\(\)/);
  assert.match(worker, /OWNER_TEST_RECIPIENT_MSISDN/);
  assert.match(worker, /owner_test\.outbound_message_requested/);
  assert.doesNotMatch(worker, /outbound_message_requested[^\n]*recipient/);
  assert.match(worker, /COALESCE\(wc\.phone_number_id, c\.phone_number_id\) AS phone_number_id/);
  assert.match(worker, /LEFT JOIN tenant_whatsapp_connections wc ON wc\.client_id = c\.id/);
  assert.match(worker, /path === '\/internal\/owner-test\/credential-health'/);
  assert.match(worker, /PORTAL_CORE_SHARED_SECRET/);
  assert.match(worker, /internal\/owner-test\/renew-credential/);
  assert.match(worker, /owner_test\.credential_renewed/);
  assert.match(worker, /owner_test\.credential_health_checked/);
  assert.doesNotMatch(worker, /FROM clients WHERE id = 1/);
  assert.match(worker, /WHERE client_id = \?\n\s*`\)\.bind\(ownerTenant\.id\)/);
  assert.match(worker, /owner_test\.message_requested', ownerTenant\.id/);
});
